[project]
name = "comfyui_baikong_node"
description = "Nodes:BK Img To Color, BK Color Selector"
version = "1.0.2"
license = { file = "LICENSE" }
dependencies = ["colornamer>=0.2.4", "scikit_learn>=1.4.0", "webcolors==1.11"]

[project.urls]
Repository = "https://github.com/JayLyu/ComfyUI_BaiKong_Node"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "baikong"
DisplayName = "ComfyUI_BaiKong_Node"
Icon = ""
